pipeline {
    agent any

    stages {
        stage('Quality Gate status') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh './gradlew sonarqube'
                }
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                }
            }
        }
    }
}
