pipeline{

    agent any

    stages{
        stage('Quality Gate status'){

            
            steps{
                script{
                        waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                }
            }
        }
        
    }
}
